### ISSUE TITLE
Takes long time to train

### ISSUE THREAD

**Issue by ryookumura** [apardyl/AdaGlimpse#1]
Thank you for your great work!
I'm trying to train a model for ImageNet1K classification task.

In my computational environment, one epoch requires 600,540 training steps and the training advances about four steps per sec, that means it takes 174 days for 100 epochs... Is the problem in the computing environment or in my training settings?

Here's my environment.
  CPU: Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz
  GPU: NVIDIA GeForce RTX 3090  x 2
  NVIDIA driver: 535.171.04
  OS: Ubuntu 20.04.6 LTS
  CUDA: 12.1
  pytorch: 2.2.2

Here's my hyper parameters.
[hparams.txt](https://github.com/apardyl/AdaGlimpse/files/15102270/hparams.txt)

Also, could you share your hyperparameters to reproduce results in your paper for ImageNet1K classification task and pretraining?
I could not find some parameters like early stopping threshold etc.

**Comment by apardyl** [comment]
Hi @ryookumura, thank you for taking interest in our research!

Training of AdaGlimpse is slow, taking about 1 week on 4 x NVIDIA A100 machine for 100 epochs ImageNet-1k experiment. However, the 174 days you mentioned seems like an error. Unfortunately, I do not have access to any RTX3090 to check it. My best guess is that it might be due to a bug in one of dependencies - I've had similar problems with some versions of the `timm` package this project is based on. Please find attached a list of package versions we use: 
[packages.txt](https://github.com/user-attachments/files/16420244/packages.txt)

The hyper-parameters you use seem correct, I've added full command line prompts we used to README.

Finally, as our paper was recently accepted to ECCV 2024, we have also released pre-trained models to [https://huggingface.co/apardyl/AdaGlimpse/tree/main](https://huggingface.co/apardyl/AdaGlimpse/tree/main).
